# Generated by Django 3.1.6 on 2021-02-14 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttitudeToAlcohol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Отношение к алкоголю',
                'verbose_name_plural': 'Отношения к алкоголю',
            },
        ),
        migrations.CreateModel(
            name='AttitudeToSmoking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Отношение к курению',
                'verbose_name_plural': 'Отношения к курению',
            },
        ),
        migrations.CreateModel(
            name='AvailabilityOfHousing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Наличие собственного жилья',
                'verbose_name_plural': 'Наличие собственного жилья',
            },
        ),
        migrations.CreateModel(
            name='BodyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Телосложение',
                'verbose_name_plural': 'Телосложения',
            },
        ),
        migrations.CreateModel(
            name='CharacteristicsOfZodiac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Характеристика (Знака зодиака)',
                'verbose_name_plural': 'Характеристика (Знака зодиака)',
            },
        ),
        migrations.CreateModel(
            name='CharacterTraits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Черта характера',
                'verbose_name_plural': 'Черты характера',
            },
        ),
        migrations.CreateModel(
            name='ColoursOfZodiac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Цвет (Знака зодиака)',
                'verbose_name_plural': 'Цвета (Знака зодиака)',
            },
        ),
        migrations.CreateModel(
            name='ControlOfPlanet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Контролирующая планета (Знака зодиака)',
                'verbose_name_plural': 'Контролирующие планеты (Знака зодиака)',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Образование',
                'verbose_name_plural': 'Образования',
            },
        ),
        migrations.CreateModel(
            name='Elements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Элемент стихии',
                'verbose_name_plural': 'Элементы стихий',
            },
        ),
        migrations.CreateModel(
            name='EyeColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Цвет глаз',
                'verbose_name_plural': 'Цвета глаз',
            },
        ),
        migrations.CreateModel(
            name='FlowersOfZodiac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Цветок (Знака зодиака)',
                'verbose_name_plural': 'Цветы (Знака зодиака)',
            },
        ),
        migrations.CreateModel(
            name='HairColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Цвет волос',
                'verbose_name_plural': 'Цвета волос',
            },
        ),
        migrations.CreateModel(
            name='HousingConditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Жилищные условия',
                'verbose_name_plural': 'Жилищные условия',
            },
        ),
        migrations.CreateModel(
            name='ManagingHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Управляющий дом (Знака зодиака)',
                'verbose_name_plural': 'Управляющие дома (Знака зодиака)',
            },
        ),
        migrations.CreateModel(
            name='MaritalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Семейное положение',
                'verbose_name_plural': 'Семейные положения',
            },
        ),
        migrations.CreateModel(
            name='MaterialStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Материальное положение',
                'verbose_name_plural': 'Материальные положения',
            },
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Национальность',
                'verbose_name_plural': 'Национальности',
            },
        ),
        migrations.CreateModel(
            name='PlaceOfResidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Место проживания',
                'verbose_name_plural': 'Места проживания',
            },
        ),
        migrations.CreateModel(
            name='QualityOfZodiac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Качество (Знака зодиака)',
                'verbose_name_plural': 'Качества (Знака зодиака)',
            },
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Вероисповедание',
                'verbose_name_plural': 'Вероисповедания',
            },
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Пол',
                'verbose_name_plural': 'Пол',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
            },
        ),
        migrations.CreateModel(
            name='StoneFortuneOfZodiac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Камень удачи (Знака зодиака)',
                'verbose_name_plural': 'Камни удачи (Знака зодиака)',
            },
        ),
        migrations.CreateModel(
            name='TarotCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Карта Таро (Знака зодиака)',
                'verbose_name_plural': 'Карты Таро (Знака зодиака)',
            },
        ),
        migrations.CreateModel(
            name='ZodiacSign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название знака зодиака')),
                ('characteristics', models.ManyToManyField(to='guide.CharacteristicsOfZodiac', verbose_name='Характеристики знака')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.coloursofzodiac', verbose_name='Цвет знака')),
                ('compatibil', models.ManyToManyField(related_name='_zodiacsign_compatibil_+', to='guide.ZodiacSign', verbose_name='Лучшая совместимость')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.elements', verbose_name='Элемент знака')),
                ('flowers', models.ManyToManyField(to='guide.FlowersOfZodiac', verbose_name='Цветы')),
                ('manhome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.managinghome', verbose_name='Управляющий дом')),
                ('planets', models.ManyToManyField(to='guide.ControlOfPlanet', verbose_name='Управляющие планеты')),
                ('quality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.qualityofzodiac', verbose_name='Качество знака')),
                ('stones', models.ManyToManyField(to='guide.StoneFortuneOfZodiac', verbose_name='Камни удачи')),
                ('tarot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.tarotcard', verbose_name='Карта Таро')),
            ],
            options={
                'verbose_name': 'Знак зодиака',
                'verbose_name_plural': 'Знаки зодиака',
            },
        ),
    ]
