# Generated by Django 3.1.6 on 2021-02-14 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarriedAnkets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Отчество')),
                ('birthday', models.DateField()),
                ('fullyears', models.IntegerField(verbose_name='Полных лет')),
                ('place_of_work', models.TextField(max_length=200, verbose_name='Место работы')),
                ('position', models.TextField(max_length=100, verbose_name='Должность')),
                ('children', models.BooleanField(default=False, verbose_name='Наличие детей')),
                ('children_locations', models.TextField(max_length=200, verbose_name='При наличии детей: место их проживания')),
                ('car', models.BooleanField(default=False, verbose_name='Наличие личного автомобиля')),
                ('height', models.IntegerField(verbose_name='Рост')),
                ('weight', models.IntegerField(verbose_name='Вес')),
                ('hobby', models.TextField(max_length=1000, verbose_name='Интересы/хобби, какими видами спорта занимаетесь, как и где проводите свободное время')),
                ('life_priorities', models.TextField(max_length=1000, verbose_name='Жизненные ценности, приоритеты')),
                ('life_credo', models.TextField(max_length=200, verbose_name='Жизненное кредо/девиз')),
                ('phone', models.CharField(max_length=11, verbose_name='Номер телефона для связи')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('time_contact', models.CharField(max_length=50, verbose_name='Удобное время для связи')),
                ('address', models.TextField(max_length=1000, verbose_name='Адрес проживания')),
                ('condition_dispensary', models.TextField(max_length=200, verbose_name='Состоит ли клиент в диспансере')),
                ('criminal_record', models.TextField(max_length=500, verbose_name='Бал ли судим, если Да по каким квалификациям')),
                ('childfree', models.BooleanField(default=True, verbose_name='Планируете ли детей в браке?')),
                ('clienttime', models.CharField(max_length=100, verbose_name='На какое время планирует быть нашим клиентом')),
                ('attitude_to_alcohol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.attitudetoalcohol', verbose_name='Отношение к алкоголю')),
                ('body_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.bodytype', verbose_name='Телосложение')),
                ('character_traits', models.ManyToManyField(to='guide.CharacterTraits', verbose_name='Присущие черты характера')),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.education', verbose_name='Образование')),
                ('eye_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.eyecolor', verbose_name='Цвет глаз')),
                ('hair_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.haircolor', verbose_name='Цвет волос')),
                ('housing_conditions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.housingconditions', verbose_name='Жилищные условия')),
                ('marital_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.maritalstatus', verbose_name='Семейное положение')),
                ('material_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.materialstatus', verbose_name='Материальное положение')),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.nationality', verbose_name='Национальность')),
                ('religion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.religion', verbose_name='Вероисповедение')),
                ('sex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.sex', verbose_name='Пол')),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.specialty', verbose_name='Специальность')),
                ('zodiacsign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.zodiacsign', verbose_name='Знак зодиака')),
            ],
            options={
                'verbose_name': 'Анкета клиента',
                'verbose_name_plural': 'Анкеты клиентов',
            },
        ),
        migrations.CreateModel(
            name='ClientRequirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_in', models.PositiveIntegerField(verbose_name='Возраст от')),
                ('age_out', models.PositiveIntegerField(verbose_name='Возраст до')),
                ('height', models.IntegerField(verbose_name='Рост')),
                ('weight', models.IntegerField(verbose_name='Вес')),
                ('presence_of_children', models.BooleanField(default=False, verbose_name='Наличие детей у партнера')),
                ('not_needed', models.TextField(max_length=1000, verbose_name='Какой партнер не нужен')),
                ('remm', models.TextField(max_length=2000, verbose_name='Дополнительная информация')),
                ('date_create', models.DateField(verbose_name='Дата создания анкеты')),
                ('attitude_to_alcohol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.attitudetoalcohol', verbose_name='Отношение к алкоголю')),
                ('attitude_to_smoking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.attitudetosmoking', verbose_name='Отношение к курению')),
                ('availability_of_housing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.availabilityofhousing', verbose_name='Наличие жилья у партнера')),
                ('body_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.bodytype', verbose_name='Телосложение')),
                ('character_traits', models.ManyToManyField(to='guide.CharacterTraits', verbose_name='Важные качества характера партнера')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='married.marriedankets', verbose_name='Клиент')),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.education', verbose_name='Образование')),
                ('eye_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.eyecolor', verbose_name='Цвет глаз')),
                ('hair_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.haircolor', verbose_name='Цвет волос')),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.nationality', verbose_name='Национальность')),
                ('place_of_residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.placeofresidence', verbose_name='Место проживания')),
                ('religion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.religion', verbose_name='Вероисповедение')),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.specialty', verbose_name='Специальность')),
                ('zodiacsign', models.ManyToManyField(to='guide.ZodiacSign', verbose_name='Знак зодиака')),
            ],
            options={
                'verbose_name': 'Требования клиентов',
                'verbose_name_plural': 'Требования клиентов',
            },
        ),
    ]
