from django.contrib import admin
from .models import *


admin.site.register(ZodiacSign)
admin.site.register(Education)
admin.site.register(Specialty)
admin.site.register(MaterialStatus)
admin.site.register(MaritalStatus)
admin.site.register(HousingConditions)
admin.site.register(AttitudeToAlcohol)
admin.site.register(BodyType)
admin.site.register(EyeColor)
admin.site.register(HairColor)
admin.site.register(Religion)
admin.site.register(Nationality)
admin.site.register(CharacterTraits)
admin.site.register(Sex)
admin.site.register(PlaceOfResidence)
admin.site.register(Elements)
admin.site.register(CharacteristicsOfZodiac)
admin.site.register(QualityOfZodiac)
admin.site.register(ControlOfPlanet)
admin.site.register(ManagingHome)
admin.site.register(TarotCard)
admin.site.register(ColoursOfZodiac)
admin.site.register(StoneFortuneOfZodiac)
admin.site.register(FlowersOfZodiac)